import type { ReactNode } from 'react';
import type { Campaign, CampaignStatus, CampaignTemplate, CreateCampaignInput } from './types';

export function CampaignStatusBadge({ status }: { status: CampaignStatus }) {
  const tone = status === 'completed' ? 'success' : status === 'cancelled' ? 'danger' : status === 'running' ? 'accent' : status === 'scheduled' ? 'warning' : 'neutral';
  return <span className={`ax-badge ax-badge--soft ax-badge--pill ax-badge--${tone}`}><span className="ax-badge__dot" />{status[0].toUpperCase() + status.slice(1)}</span>;
}

export function CampaignFilters({ search, status, templateId, templates, onSearch, onStatus, onTemplate }: { search: string; status: CampaignStatus | 'all'; templateId: string; templates: CampaignTemplate[]; onSearch: (value: string) => void; onStatus: (value: CampaignStatus | 'all') => void; onTemplate: (value: string) => void }) {
  return <div className="ax-cluster" style={{ gap: 'var(--ax-space-3)', flexWrap: 'wrap', marginBlockEnd: 'var(--ax-space-5)' }}>
    <div className="ax-field" style={{ minWidth: 220, flex: '1 1 260px' }}><label className="ax-label" htmlFor="campaign-search">Search campaigns</label><input id="campaign-search" className="ax-input" value={search} onChange={(event) => onSearch(event.target.value)} placeholder="Search by name" /></div>
    <div className="ax-field"><label className="ax-label" htmlFor="campaign-status">Status</label><select id="campaign-status" className="ax-select" value={status} onChange={(event) => onStatus(event.target.value as CampaignStatus | 'all')}><option value="all">All statuses</option>{(['draft', 'scheduled', 'running', 'completed', 'cancelled'] as CampaignStatus[]).map((value) => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></div>
    <div className="ax-field"><label className="ax-label" htmlFor="campaign-template">Template</label><select id="campaign-template" className="ax-select" value={templateId} onChange={(event) => onTemplate(event.target.value)}><option value="all">All templates</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div>
  </div>;
}

export function CampaignTable({ campaigns, templates, onView, onDispatch, onDelete }: { campaigns: Campaign[]; templates: CampaignTemplate[]; onView: (campaign: Campaign) => void; onDispatch?: (campaign: Campaign) => void; onDelete?: (campaign: Campaign) => void }) {
  const templateName = (id: string) => templates.find((template) => template.id === id)?.name ?? id;
  return <section className="ax-card ax-col--12" role="region" aria-label="Campaigns"><div className="ax-card__header"><div className="ax-card__titles"><h2 className="ax-card__title">Campaigns</h2><p className="ax-card__subtitle">{campaigns.length} campaign{campaigns.length === 1 ? '' : 's'}</p></div></div><div className="ax-table-wrap"><table className="ax-table ax-table--hover"><thead className="ax-table__head"><tr>{['Campaign', 'Template', 'Target', 'Scheduled', 'Status', 'Actions'].map((heading) => <th className="ax-table__th" scope="col" key={heading}>{heading}</th>)}</tr></thead><tbody>{campaigns.map((campaign) => <tr className="ax-table__row" key={campaign.id}><td className="ax-table__td"><div style={{ fontWeight: 'var(--ax-weight-medium)', color: 'var(--ax-text-strong)' }}>{campaign.name}</div><div className="ax-num" style={{ color: 'var(--ax-text-subtle)', fontSize: 'var(--ax-text-xs)' }}>{campaign.id}</div></td><td className="ax-table__td">{templateName(campaign.templateId)}</td><td className="ax-table__td">{campaign.targeting.targetSegment}<br /><span style={{ color: 'var(--ax-text-muted)', fontSize: 'var(--ax-text-xs)' }}>{campaign.targeting.targetMode}{campaign.targeting.targetSamplePercent ? ` · ${campaign.targeting.targetSamplePercent}%` : ''}</span></td><td className="ax-table__td">{campaign.scheduledAt ? new Date(campaign.scheduledAt).toLocaleString() : 'Immediate'}</td><td className="ax-table__td"><CampaignStatusBadge status={campaign.status} /></td><td className="ax-table__td" style={{ whiteSpace: 'nowrap' }}>{(campaign.status === 'draft' || campaign.status === 'scheduled') && onDispatch && (<button type="button" className="ax-btn ax-btn--primary ax-btn--sm" style={{ marginRight: 'var(--ax-space-2)' }} onClick={(e) => { e.stopPropagation(); onDispatch(campaign); }}>Dispatch</button>)}<button type="button" className="ax-btn ax-btn--ghost ax-btn--sm" onClick={() => onView(campaign)}>Open</button>{(campaign.status === 'draft' || campaign.status === 'completed') && onDelete && <button type="button" className="ax-btn ax-btn--danger ax-btn--sm" style={{ marginLeft: 'var(--ax-space-2)' }} onClick={() => onDelete(campaign)}>Delete</button>}</td></tr>)}</tbody></table></div></section>;
}

export function CampaignReview({ input, template }: { input: CreateCampaignInput; template?: CampaignTemplate }) {
  return <section className="ax-card" role="region" aria-label="Campaign review"><div className="ax-card__header"><div className="ax-card__titles"><span className="ax-card__eyebrow">Review</span><h2 className="ax-card__title">Campaign configuration</h2></div></div><dl className="ax-card__body" style={{ display: 'grid', gap: 'var(--ax-space-3)', margin: 0 }}>{[['Name', input.name], ['Template', template?.name ?? input.templateId], ['Target mode', input.targetMode], ['Target segment', input.targetSegment], ['Sample', input.targetSamplePercent === null ? 'Not set' : `${input.targetSamplePercent}%`], ['Stagger window', `${input.staggerWindowMinutes} minutes`], ['Schedule', input.scheduledAt ? new Date(input.scheduledAt).toLocaleString() : 'Send immediately']].map(([label, value]) => <div key={label} className="ax-cluster" style={{ justifyContent: 'space-between', gap: 'var(--ax-space-4)' }}><dt style={{ color: 'var(--ax-text-muted)' }}>{label}</dt><dd style={{ margin: 0, color: 'var(--ax-text-strong)' }}>{value}</dd></div>)}</dl></section>;
}

export function ConfirmDialog({ title, body, confirmLabel, onCancel, onConfirm }: { title: string; body: ReactNode; confirmLabel: string; onCancel: () => void; onConfirm: () => void }) {
  return <div role="presentation" onMouseDown={(event) => event.target === event.currentTarget && onCancel()} style={{ position: 'fixed', inset: 0, zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 'var(--ax-space-4)', background: 'rgba(15,18,25,.5)' }}><div className="ax-card" role="alertdialog" aria-modal="true" style={{ maxWidth: 460, width: '100%' }}><div className="ax-card__header"><h2 className="ax-card__title">{title}</h2></div><div className="ax-card__body"><p style={{ margin: 0, color: 'var(--ax-text-muted)' }}>{body}</p></div><div className="ax-card__footer ax-cluster" style={{ justifyContent: 'flex-end', gap: 'var(--ax-space-3)' }}><button type="button" className="ax-btn ax-btn--secondary" onClick={onCancel}>Keep</button><button type="button" className="ax-btn ax-btn--danger" onClick={onConfirm}>{confirmLabel}</button></div></div></div>;
}
